site_name: obsidian-mkdocs template

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        
features:
    - navigation.sections
    - navigation.indexes

nav:
    - Obsidian Notes: docs/index.md
    - Features:
        - docs/Features/index.md
        - LaTeX Math Support: docs/Features/LaTeX Math Support.md
        - Mermaid diagrams: docs/Features/Mermaid Diagrams.md
        - Text Formatting: docs/Features/Text Formatting.md
    - Topic 1:
        - docs/Topic 1/index.md
        - Note 1: docs/Topic 1/Note 1.md
        - Note 2: docs/Topic 1/Note 2.md

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - mermaid2

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
